### ISSUE TITLE
Using images as resource file

### ISSUE THREAD

**Issue by mharizanov** [lvgl/lvgl#706]
Hello,

Instead of having multipple image resources, it is sometimes useful to combine several images into one, and then visualise a "window" of it. 
As an example, WiFi strength indicator (credit to Moddable), but same will apply to battery levels etc:

![Image as resource](https://raw.githubusercontent.com/Moddable-OpenSource/moddable/public/examples/piu/wifi-config/assets/wifi-strip.png)

Is there a way that this sort of image resource can be used in LittlevGL?

**Comment by seyyah** [comment]
This idea is known as image sprite at web tech [1].

For example, sprites.png (132x44px),

![sprite](https://user-images.githubusercontent.com/263237/50723101-1d364b80-10ea-11e9-8248-cbcb8edf3c55.png)

```css
#home {
  height: 44px;
  width: 46px;
  background: url('sprites.png') 0 0;
}

#prev {
  height: 44px;
  width: 43px;
  background: url('sprites.png') -47px 0;
}

#next {
  height: 44px;
  width: 43px;
  background: url('sprites.png') -91px 0;
}
```

`height` and `width` parameters are subimage's size. `0px, -47px, -91px` are shift left amount.

I don't know any practical way in the LittlevGL.



## :clipboard: Reference
1. https://www.w3schools.com/css/css_image_sprites.asp
